### ISSUE TITLE
Android6.0以上使用

### ISSUE THREAD

**Issue by AXwjg** [licheedev/Android-SerialPort-API#16]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fjx.com.bigdomesticgarbage, PID: 13908
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/fjx.com.bigdomesticgarbage-2/lib/arm/libserial_port.so: has text relocations
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at android.serialport.SerialPort.<clinit>(SerialPort.java:111)
        at com.zg.zgseriallibrary.serial.SerialPortManager.open(SerialPortManager.java:44)
        at com.zg.zgseriallibrary.serial.VendingCabinets2.openSerialPort(VendingCabinets2.java:40)
        at fjx.com.bigdomesticgarbage.activity.MainActivity.initZG(MainActivity.java:874)
        at fjx.com.bigdomesticgarbage.activity.MainActivity.onCreate(MainActivity.java:146)
        at android.app.Activity.performCreate(Activity.java:6266)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

![image](https://user-images.githubusercontent.com/29494868/66975708-e1490180-f0d1-11e9-894f-c6a2ab24c7cb.png)

**Comment by licheedev** [comment]
工程的abi配置是怎样的，新版本的ndk删除了对部分abi的支持，生成的so是没有armeabi、mips、mips64目录的。
